version: "2.9"

services:
  mysqldb:
    container_name: simple-crm-db
    image: mysql:8.0.32
    networks:
      - simple-crm-network
    restart: on-failure
    environment:
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password123!
      - MYSQL_DATABASE=simple-crm
      - MYSQL_ROOT_PASSWORD=rootpassword123!
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD-SHELL", 'mysql --database=$$MYSQL_DATABASE --password=$$MYSQL_ROOT_PASSWORD
      --execute="SELECT COUNT(*) FROM information_schema.tables"']
      start_period: 30s
      retries: 20
    volumes:
      - dbvol:/var/lib/mysql
  app:
    container_name: simple-crm-app
    networks:
      - simple-crm-network
    restart: on-failure
    depends_on:
      mysqldb:
        condition: service_healthy
    build:
      context: .
    ports:
      - "8080:8080"

networks:
  simple-crm-network:
    name: simple-crm-network

volumes:
  dbvol: